package best.tigers.tynkdialog.gui.view.components.neo;

import javax.swing.*;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import java.awt.*;
import java.util.function.BiConsumer;
import java.util.function.Consumer;

public class NeoScrollingListEditor<T> {
    private JPanel rootPanel;
    private JList<T> list;
    private JButton addResponseButton;
    private JButton moveDownResponseButton;
    private JButton deleteResponseButton;
    private JButton moveUpResponseButton;
    private JScrollPane scrollPane;
    private JToolBar controlStrip;

    public NeoScrollingListEditor(ListModel<T> listModel) {
        setList(listModel);
    }

    public NeoScrollingListEditor() {
    }

    public JPanel getRootPanel() {
        return rootPanel;
    }

    public NeoScrollingListEditor(ListModel<T> listModel, ListCellRenderer<T> renderer) {
        this(listModel);
        list.setCellRenderer(renderer);
    }

    public void setAddAction(Runnable r) {
        addResponseButton.addActionListener(e -> r.run());
    }

    public void setDeleteItemAction(Consumer<Integer> indexConsumer) {
        deleteResponseButton.addActionListener(e -> indexConsumer.accept(list.getSelectedIndex()));
    }

    public void setMoveUpAction(BiConsumer<Integer, Consumer<int[]>> indexConsumer) {
        moveUpResponseButton.addActionListener(
                e -> indexConsumer.accept(list.getSelectedIndex(), list::setSelectedIndices));
    }

    public void setMoveDownAction(BiConsumer<Integer, Consumer<int[]>> indexConsumer) {
        moveDownResponseButton.addActionListener(
                e -> indexConsumer.accept(list.getSelectedIndex(), list::setSelectedIndices));
    }

    public JList<T> getList() {
        return list;
    }

    public void setList(ListModel<T> newListModel) {
        list.setModel(newListModel);
    }

    public void setListSelectionAction(Consumer<T> valueConsumer) {
        list.addListSelectionListener(e -> valueConsumer.accept(list.getSelectedValue()));
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        rootPanel = new JPanel();
        rootPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 1, new Insets(5, 5, 5, 5), -1, -1));
        scrollPane = new JScrollPane();
        rootPanel.add(scrollPane, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        list = new JList();
        scrollPane.setViewportView(list);
        controlStrip = new JToolBar();
        rootPanel.add(controlStrip, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(-1, 20), null, 0, false));
        addResponseButton = new JButton();
        addResponseButton.setText("Add");
        controlStrip.add(addResponseButton);
        deleteResponseButton = new JButton();
        deleteResponseButton.setText("Delete");
        controlStrip.add(deleteResponseButton);
        moveUpResponseButton = new JButton();
        moveUpResponseButton.setText("Up");
        controlStrip.add(moveUpResponseButton);
        moveDownResponseButton = new JButton();
        moveDownResponseButton.setText("Down");
        controlStrip.add(moveDownResponseButton);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPanel;
    }
}
