package best.tigers.tynkdialog.newgui.view;

import best.tigers.tynkdialog.newgui.model.AbstractPageBean;
import best.tigers.tynkdialog.newgui.model.DialogBean;
import best.tigers.tynkdialog.newgui.model.FlatPageBean;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;

public class DialogBeanView implements PropertyChangeListener {
    private JList<AbstractPageBean> pageBeanList;
    private JPanel dialogBeanPanel;
    private JTextField titleField;
    private JButton saveChangesButton;
    private JButton addButton;
    private DialogBean dialogBean;

    public DialogBeanView(DialogBean dialogBean) {
        this.dialogBean = dialogBean;
        $$$setupUI$$$();
        pageBeanList.setModel(this.dialogBean);
        dialogBean.addPropertyChangeListener(this);
        saveChangesButton.addActionListener(e -> this.saveChanges());
        addButton.addActionListener(e -> {
            dialogBean.addPage(new FlatPageBean());
        });
        pageBeanList.addListSelectionListener((s) -> {
            var index = s.getFirstIndex();
            var newFrame = new JFrame();
            newFrame.add(new FlatPageBeanView((FlatPageBean) dialogBean.getElementAt(index)).getPanel());
            newFrame.pack();
            newFrame.setVisible(true);
        });
    }

    public void detach() {
        dialogBean.removePropertyChangeListener(this);
    }

    public JPanel getPanel() {
        return dialogBeanPanel;
    }

    private void createUIComponents() {
        pageBeanList = new JList<>();
    }

    @Override
    public void propertyChange(PropertyChangeEvent evt) {
        if (evt.getSource() instanceof DialogBean bean && bean.equals(dialogBean)) {
            if (evt.getPropertyName().equals("title")) {
                titleField.setText(dialogBean.getTitle());
            }
        }
    }

    public void saveChanges() {
        dialogBean.setTitle(titleField.getText());
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        dialogBeanPanel = new JPanel();
        dialogBeanPanel.setLayout(new GridLayoutManager(4, 2, new Insets(10, 10, 10, 10), -1, -1));
        titleField = new JTextField();
        dialogBeanPanel.add(titleField, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JLabel label1 = new JLabel();
        label1.setText("Title");
        dialogBeanPanel.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("Pages");
        dialogBeanPanel.add(label2, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_NORTHWEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        dialogBeanPanel.add(pageBeanList, new GridConstraints(1, 1, 2, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
        saveChangesButton = new JButton();
        saveChangesButton.setText("Save Changes");
        dialogBeanPanel.add(saveChangesButton, new GridConstraints(3, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return dialogBeanPanel;
    }

}
